name: 'Get Repository Information'

description: 'Access repository information even if not available natively on GitHub'

author: 'Fr Platform'

branding:
  icon: 'printer'  
  color: 'purple'

inputs:
  repository:
    description: "Name of Repository's owner and name"
    required: false
    default: '${{ github.repository }}'

outputs:
  repository-owner:
    description: "Repository's owner"
    value: ${{ steps.get-repository-info.outputs.owner }}
    
  repository-name:
    description: "Repository's name"
    value: ${{ steps.get-repository-info.outputs.name }}

runs:
  using: "composite"
  steps:
    - name: Get Repository Information
      id: get-repository-info
      run: |
        IN=${{ inputs.repository }}
        repository=(${IN//// })
        owner=$(echo ${repository[0]} | tr '[:upper:]' '[:lower:]')
        name=$(echo ${repository[1]} | tr '[:upper:]' '[:lower:]')
        echo $owner
        echo $name
        echo "::set-output name=repository-owner::$owner"
        echo "::set-output name=repository-name::$name"
      shell: bash
