name: CI

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run the Action
        uses: fr-platform/github-action-get-repo-info@v0.0.3
        id: get-repo
        
      - name: Echo Outputs
        run: |
          echo "${{ steps.get-repo.outputs.repository-owner }}"
          echo "${{ steps.get-repo.outputs.repository-name }}"
