name: Run Action

on: [push]

jobs:
  run-action:
    runs-on: ubuntu-latest
    name: Run Action
    steps:
      - name: Run the Action
        uses: fr-platform/github-action-get-repo-info@v0.0.7
        id: get-repo
        
      - name: Echo Outputs
        run: |
          echo ${{ steps.get-repo.outputs.repository-owner }}
          echo ${{ steps.get-repo.outputs.repository-name }}
